"""Update - Change Users, + Requests Table

Revision ID: bf84a8d21ee7
Revises: 99212e98b389
Create Date: 2020-09-11 05:12:45.508405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf84a8d21ee7'
down_revision = '99212e98b389'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=True),
    sa.Column('post_date', sa.DateTime(), nullable=True),
    sa.Column('body', sa.String(length=500), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requests_post_date'), 'requests', ['post_date'], unique=False)
    op.add_column('user', sa.Column('phone_number', sa.Unicode(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'phone_number')
    op.drop_index(op.f('ix_requests_post_date'), table_name='requests')
    op.drop_table('requests')
    # ### end Alembic commands ###
